easy_admin:
    list:
        title: 'list of %%entity_label%%'
    entities:

        # List the entity class name you want to manage
        Survey:
            class: App\Entity\Survey
        Question:
            class: App\Entity\Question
        QuestionsType:
            class: App\Entity\QuestionType
        User:
            class: App\Entity\User
        Blog:
            class: App\Entity\Blog
            form:
                    fields:
                        - { property: "Title" }
                        - { property: 'Text', type: 'text_editor'}

