# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

# config/packages/twig.yaml
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'